### ISSUE TITLE
does the sitemap "date" field mean date of creation of page? Or last date modified?

### ISSUE THREAD

**Issue by fedWikiBackup** [fedWikiBackup/howSitesAreBackedUpToThisGithubAccount#1]

**Comment by WardCunningham** [comment]
We use the date of the last Action that is not a fork. This has the advantage that unmodified forks have the same date as the page forked and thus show adjoined side by side in recent changes.

This is the code that is used.
https://github.com/fedwiki/wiki-server/blob/26b80f22057655f3463f6bc9a04a097d54eb2e1b/lib/sitemap.coffee#L40-L45

Old sitemaps from ruby might use file modification date but this is unreliable because it can be changed by file utilities.

Very old pages might not have dates in their Actions.

**Comment by WardCunningham** [comment]
If you were to only fetch pages that have a newer sitemap date than the last scan then you would miss forks without changes. We accept this consequence when we scrape sites. It has fooled me when I fork a page from a a site thinking that will cause the scraper to find that site. Not so, unless I also make a trivial edit.
